# -*- coding: utf-8 -*-

from boto3_dataclass.models.typed_dict import (
    TypedDictFieldAnnotation,
    TypedDictField,
    TypedDictDef,
    TypedDefsModule,
)

tdds = [
    TypedDictDef(
        name="SimpleModelTypeDef",
        fields=[
            TypedDictField(
                name="attr1",
            ),
        ],
    ),
    TypedDictDef(
        name="SimpleModelWithSubscriptTypeDef",
        fields=[
            TypedDictField(name="attr1"),
            TypedDictField(name="attr2"),
            TypedDictField(name="attr3"),
        ],
    ),
    TypedDictDef(
        name="SimpleModelWithNestedSubscriptTypeDef",
        fields=[
            TypedDictField(name="attr1"),
            TypedDictField(name="attr2"),
        ],
    ),
    TypedDictDef(
        name="SimpleContainerTypeDef",
        fields=[
            TypedDictField(
                name="attr1",
                anno=TypedDictFieldAnnotation(
                    is_nested_typed_dict=True,
                    nested_type_name="SimpleModelTypeDef",
                ),
            ),
            TypedDictField(
                name="attr2",
                anno=TypedDictFieldAnnotation(
                    is_nested_typed_dict=True,
                    nested_type_name="SimpleModelTypeDef",
                ),
            ),
            TypedDictField(
                name="attr3",
                anno=TypedDictFieldAnnotation(
                    is_nested_typed_dict=True,
                    nested_type_name="SimpleModelTypeDef",
                ),
            ),
            TypedDictField(
                name="attr4",
                anno=TypedDictFieldAnnotation(
                    is_nested_typed_dict=True,
                    nested_type_name="SimpleModelTypeDef",
                ),
            ),
            TypedDictField(
                name="attr5",
                anno=TypedDictFieldAnnotation(
                    is_nested_typed_dict=True,
                    nested_type_name="SimpleModelTypeDef",
                ),
            ),
            TypedDictField(
                name="attr6",
                anno=TypedDictFieldAnnotation(
                    is_nested_typed_dict=True,
                    nested_type_name="SimpleModelTypeDef",
                ),
            ),
            TypedDictField(
                name="attr7",
                anno=TypedDictFieldAnnotation(
                    is_nested_typed_dict=True,
                    nested_type_name="SimpleModelTypeDef",
                    nested_type_subscriptor="List",
                ),
            ),
            TypedDictField(
                name="attr8",
                anno=TypedDictFieldAnnotation(
                    is_nested_typed_dict=True,
                    nested_type_name="SimpleModelTypeDef",
                    nested_type_subscriptor="List",
                ),
            ),
            TypedDictField(
                name="attr9",
                anno=TypedDictFieldAnnotation(
                    is_nested_typed_dict=True,
                    nested_type_name="SimpleModelTypeDef",
                    nested_type_subscriptor="List",
                ),
            ),
        ],
    ),
    TypedDictDef(
        name="UserTypeDef",
        fields=[
            TypedDictField(
                name="id",
            ),
            TypedDictField(
                name="name",
            ),
            TypedDictField(
                name="attr1",
                anno=TypedDictFieldAnnotation(
                    is_nested_typed_dict=True,
                    nested_type_name="SimpleModelTypeDef",
                ),
            ),
            TypedDictField(
                name="attr2",
                anno=TypedDictFieldAnnotation(
                    is_nested_typed_dict=True,
                    nested_type_name="SimpleModelTypeDef",
                ),
            ),
            TypedDictField(
                name="attr3",
                anno=TypedDictFieldAnnotation(
                    is_nested_typed_dict=True,
                    nested_type_name="SimpleModelTypeDef",
                ),
            ),
            TypedDictField(
                name="attr4",
                anno=TypedDictFieldAnnotation(
                    is_nested_typed_dict=True,
                    nested_type_name="SimpleModelTypeDef",
                ),
            ),
            TypedDictField(
                name="attr5",
                anno=TypedDictFieldAnnotation(
                    is_nested_typed_dict=True,
                    nested_type_name="SimpleModelTypeDef",
                ),
            ),
            TypedDictField(
                name="attr6",
                anno=TypedDictFieldAnnotation(
                    is_nested_typed_dict=True,
                    nested_type_name="SimpleModelTypeDef",
                ),
            ),
            TypedDictField(
                name="attr7",
                anno=TypedDictFieldAnnotation(
                    is_nested_typed_dict=True,
                    nested_type_name="SimpleModelTypeDef",
                    nested_type_subscriptor="List",
                ),
            ),
            TypedDictField(
                name="attr8",
                anno=TypedDictFieldAnnotation(
                    is_nested_typed_dict=True,
                    nested_type_name="SimpleModelTypeDef",
                    nested_type_subscriptor="List",
                ),
            ),
            TypedDictField(
                name="attr9",
                anno=TypedDictFieldAnnotation(
                    is_nested_typed_dict=True,
                    nested_type_name="SimpleModelTypeDef",
                    nested_type_subscriptor="List",
                ),
            ),
        ],
    ),
]

tdm = TypedDefsModule(tdds=tdds)
